### ISSUE TITLE
Support for v11 of Foundry

### ISSUE THREAD

**Issue by fcerezo** [Chrisrous/Chris-Sound-Module#2]
Hi

Is it posible ?
Thanks

**Comment by Chrisrous** [comment]
Hi @fcerezo, since I only use the latest version of Foundry VTT myself, unfortunately, I can't verify this for the previous version. Theoretically, it should work there as well. If you’d like to test it yourself, you can simply set the version to 11 in the module.json file. You can open this file, for example, with Notepad++.
